ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "shippingName" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "shippingPhone" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "shippingAddress" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "shippingSuburb" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "shippingState" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "shippingPostcode" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "shippingNotes" TEXT;
